    
    <script type="text/javascript" src="/extensions/players/media/js/actions_player.js?v=1.0.3"></script> 
    <link rel="stylesheet" href="/extensions/entities/media/css/entities.css?v=1.5" />
    
        <div class="page players active">

        <div class="inline-actions edit-actions inline-container">
            <div class="inline"></div>
        </div>
            
        <div class="page-views">
            
            <div class="page-view" data-view="all">                
                <div class="players">   
                    <h2>All Players</h2>
                    <div class="results"></div>                                      
                </div>                    
            </div>

            <div class="page-view" data-view="observed">                
                <div class="players">   
                    <h2>Observed players</h2>
                    <div class="results"></div>
                </div>                    
            </div>    
            
            <div class="page-view" data-view="moves">                
                <div class="players">   
                    <h2>Players moves</h2>
                    <div class="moves results"></div>
                </div>                    
            </div>              
            
        </div>
            

    
    
    <script type="text/javascript">
        
        $(document).ready(function(){
    
            switcher({ 
                key: 'editable',  
                class: 'icon-settings1', 
                value: settings.editable  ? settings.editable :  'false'},
                function(){ editable();  // => ui.js                                              
            });    
            changer({ 
                title: 'Layout', 
                key: 'players_layout', 
                values: { 'grid': 'Grid', 'box':'Boxes'},
                click: function(el){ 
                    updateSettings('players_layout',$(el).find('select').val());
                    $('.page').removeClass('view-grid view-box').addClass('view-'+$(el).find('select').val());
                },
                load: function(el){
                    $('.page').removeClass('view-grid view-box').addClass('view-'+$(el).find('select').val());
                }
            });
                
            //switcher({ key: 'swipeable', class: 'icon-swipe',  value: true},function(el){ $(el).attr('data-value',true) }); // just for info
            button({ class: 'icon-btn icon-search2' }, function(el){            

                if ($('footer #popup .search').length){ 
                    $('footer #popup').html(''); 
                    $('.popup-btn').remove();
                    $('body').removeClass('with-popup');
                }else{ 
                    button({ class: 'icon-btn popup-btn icon-clear' }, function(){ $('.popup-btn').remove(); $('footer #popup').html(''); $('body').removeClass('with-popup no-blur'); });
                    $('footer #popup').html('<div class="popup active form"><input type="text" class="search" placeholder="Find by player name or nickname" /></div>'); 
                    $('body').addClass('with-popup no-blur');
                }            
            });
            
            $(document).off('click', '.search');
            $(document).on('keyup','.search',function(){
                $('.slick-initialized').slick('slickGoTo',0);
                get_all_players($(this).val());            
            });
            
            var initialSlide = 0;
            if (mvc.view === 'observed') initialSlide = 1;
            if (mvc.view === 'moves')    initialSlide = 2;

            $('.page-views').not('.slick-initialized').slick({
                arrows:false,
                dots:false,
                infinite: true,
                initialSlide:initialSlide
            }).on('beforeChange', (event, slick, currentSlide, nextSlide) => {
                if (currentSlide !== nextSlide) { $("html").animate({scrollTop: 0}, "slow"); }
            });               
            
            get_currencies(function(){
                get_all_players();
                get_observed_players();              
            });
        });    
            
        function get_all_players(search=null){
        
            $.ajax({
                url: config.api_url,
                data: { 
                    endpoint: '/players',
                    search:search
                },
                type: 'GET',
                dataType: 'JSON',
                cache: false,
                success: function(response){  
                    if (response.success === 'false') return;                    
                               
                    $('[data-view="all"] .results').html('');
                    $.each(response.players, function(i,player){
                        
                        let el = $('<div class="view"></div>');
                        
                        if (player.avatar_type){
                            $(el).append("<img src='"+player.avatar+"' class='avatar-image' />");
                        }else{
                            $(el).append('<div class="avatar avatar-'+(player.avatar ? player.avatar : 'user')+'" style="color:'+(player.avatar_color ? player.avatar_color : 'var(--color-bg)')+'"></div>');
                        }
                        
                        $(el).append((player.country ? '<img src="/media/img/flags/'+player.country+'.svg" class="country" />' : ''))
                             .append('<div class="title">'+player.username+'</div>')
                             .append('<div class="total">'+format_price(player.margin*currencies[settings.display_currency],2)+' '+settings.display_currency+'</div>')
                             .bind('click',function(){
                                location.href = '/players/view/'+player.username;
                             });
                             
                        let btn_results = '<div class="icon-btn icon-account_balance_wallet" onclick="load_page(\'/wallet/'+player.username+'\',true)"></div>';
                        $(btn_results).bind('click',function(){
                            load_page('/wallet/'+player.username,true);
                        });
                        let btn_view = '<div class="icon-btn icon-person1" onclick="load_page(\'/players/view/'+player.username+'\',true)"></div>';
                        let actions = $('<div class="actions"></div>').append(btn_results).append(btn_view);
                        
                        let box = $('<div class="box"></div>')
                            .append(el)
                            .append('<div class="icon-bookmark_outline" data-action="observe"></div>')
                            .append(actions)
                            .attr('data-username',player.username);
                        
                        $('[data-view="all"] .results').append(box);                        
                        
                    });
                }
            });
        
        }  
        /*
        function get_ranking_players(){
        
            $.ajax({
                url: config.api_url,
                data: { 
                    endpoint: '/players',
                    ranking:'highest-total-profit'
                },
                type: 'GET',
                dataType: 'JSON',
                cache: false,
                success: function(response){  
                    if (response.success === 'false') return;                    
                               
                    $('[data-view="highest-total-margin"] .results').html('');
                    var position = 1;
                    $.each(response.players, function(i,player){
                        
                        let el = $('<div class="view"></div>')                           
                            .append('<div class="avatar avatar-'+(player.avatar ? player.avatar : 'user')+'" style="color:'+(player.avatar_color ? player.avatar_color : 'var(--color-bg)')+'"></div>')
                            .append((player.country ? '<img src="/media/img/flags/'+player.country+'.svg" class="country" />' : ''))
                            .append('<div class="position">'+(position++)+'</div>')
                            .append('<div class="title">'+player.username+'</div>')
                            .append('<div class="total">'+player.margin+' $</div>')
                            .bind('click',function(){
                                location.href = '/wallet/'+player.username;
                            });
                        let box = $('<div class="box"></div>')
                            .append(el)
                            .append('<div class="icon-bookmark_outline" data-action="observe"></div>')
                            .attr('data-username',player.username);                            
                        
                        $('[data-view="highest-total-profit"] .results').append(box);                        
                        
                    });
                }
            });        
        }
        */
        
        function get_observed_moves(){
            $.ajax({
                url: config.api_url,
                data: { 
                    endpoint: '/players/observed/moves'
                },
                type: 'GET',
                dataType: 'JSON',
                cache: false,
                success: function(response){                                          
                    
                    if (config.debug) console.log(response);
                    
                    if (!response.moves || response.moves.length === 0){
                        $('[data-view="moves"] .results').html('<div class="info-page"><div class="icon icon-clear"></div><h1>No moves yet</h1><p>Players you observe didn\'t do any moves yet.</p><div class="btn primary" onclick="$(\'.slick-initialized\').slick(\'slickGoTo\',0)">Find more players</div></div>');                           
                        return;
                    }
                    
                    $('[data-view="moves"] .results').addClass('wallet-items funds').html('');
                    $.each(response.moves, function(i,move){
                        
                        var total = move.purchased_total;
                        if (move.action === 'sell') total = move.sold_total;
                        
                        let el =  $('<div class="move box" data-id="'+move.id+'"></div>');
                        if (move.avatar_type === 'image'){
                            $(el).append('<div class="avatar-container"><img src="'+move.avatar+'" class="avatar" /></div>');
                            $(el).find('.avatar-container').bind('click',function(){
                                location.href='/players/view/'+move.username;
                            });
                        } 
                        
                        $(el).append('<div class="info"></div>');
                        $(el).find('.info').append('<div class="action">'+move.action+': <span class="symbol">'+move.symbol+'</span> ('+move.market+')</div>');
                        $(el).find('.action .symbol').bind('click',function(){
                                location.href='/entities/'+move.market+'/'+move.symbol;
                            });
                        
                        $(el).find('.info').append('<div class="date label">'+move.date+'</div>');
                        
                        $(el).append('<div class="totals"></div>');
                        $(el).find('.totals').append('<div class="total">'+(move.action === 'buy' ? '' : '+') + format_price(total *currencies[settings.display_currency],2)+' '+settings.display_currency+'</div>');
                        
                        if (move.action === 'sell'){
                            $(el).find('.totals').append('<div class="profit">'+(move.margin >= 0 ? '+' : '') + format_price(move.margin *currencies[settings.display_currency],2)+' '+settings.display_currency+'</div>');
                        }

                        $('[data-view="moves"] .results').append(el);
                        
                    });
                    
                }
            });            
        }
        
        function get_observed_players(){
        
            $.ajax({
                url: config.api_url,
                data: { 
                    endpoint: '/players/observed'
                },
                type: 'GET',
                dataType: 'JSON',
                cache: false,
                success: function(response){  
                                                             
                    if (!response.players || response.players.length === 0){
                        $('[data-view="observed"] h2').remove();
                        $('[data-view="observed"] .results').html('<div class="info-page"><div class="icon icon-clear"></div><h1>No Observed players</h1><p>You don\'t observe any player yet.</p><div class="btn primary" onclick="$(\'.slick-initialized\').slick(\'slickGoTo\',0)">Find players</div></div>')
                        
                        $('[data-view="moves"] h2').remove();
                        $('[data-view="moves"] .results').html('<div class="info-page"><div class="icon icon-clear"></div><h1>No moves</h1><p>You don\'t observe any player yet.</p><div class="btn primary" onclick="$(\'.slick-initialized\').slick(\'slickGoTo\',0)">Find players</div></div>')                        
                        return;
                    } 
                    
                    get_observed_moves();
                               
                    $('[data-view="observed"] .results').html('');
                    var position = 1;
                    $.each(response.players, function(i,player){
                        
                        let el = $('<div class="view"></div>');
                        
                        if (player.avatar_type){
                            $(el).append("<img src='"+player.avatar+"' class='avatar-image' />");
                        }else{
                            $(el).append('<div class="avatar avatar-'+(player.avatar ? player.avatar : 'user')+'" style="color:'+(player.avatar_color ? player.avatar_color : 'var(--color-bg)')+'"></div>');
                        } 
                        
                        $(el).append((player.country ? '<img src="/media/img/flags/'+player.country+'.svg" class="country" />' : ''))
                             //.append('<div class="position">'+(position++)+'</div>')
                             .append('<div class="title">'+player.username+'</div>')
                             .append('<div class="total">'+format_price(player.margin*currencies[settings.display_currency],2)+' '+settings.display_currency+'</div>')
                             .bind('click',function(){
                                location.href = '/wallet/'+player.username;
                             });
                             
                        let btn_results = '<div class="icon-btn icon-account_balance_wallet" onclick="load_page(\'/wallet/'+player.username+'\',true)"></div>';
                        $(btn_results).bind('click',function(){
                            load_page('/wallet/'+player.username,true);
                        });
                        let btn_view = '<div class="icon-btn icon-person1" onclick="load_page(\'/players/view/'+player.username+'\',true)"></div>';
                        $(btn_results).bind('click',function(){
                            load_page('/wallet/'+player.username,true);
                        });
                        let actions = $('<div class="actions"></div>').append(btn_results).append(btn_view);
                        
                        let box = $('<div class="box"></div>')
                            .append(el)
                            .append('<div class="icon-bookmark1" data-action="stop-observe"></div>')
                            .append(actions)
                            .attr('data-username',player.username);                             
                        
                        $('[data-view="observed"] .results').append(box);
                        
                        if ($('[data-username="'+player.username+'"]')){
                            $('[data-username="'+player.username+'"]').find('[data-action="observe"]')
                                .toggleClass('icon-bookmark_outline').toggleClass('icon-bookmark1')
                                .attr('data-action','stop-observe');
                        }
                        
                    });
                }
            });
        
        }
    
    </script>