    


    <link rel="stylesheet" href="/extensions/entities/media/css/entities.css?v=1.4" />
    
        <div class="page players active">

        <div class="page-views">
            <div class="page-view" data-view="all">
                
                <div class="players">   
                    <h2>All Players</h2>
                    <div class="results"></div>                                      
                </div>    
                
            </div>
            
            <div class="page-view" data-view="highest-total-profit">
                
                <div class="players">   
                    <h2>Highest Total Profit</h2>
                    <div class="results"></div>
                </div>    
                
            </div>   
            
            <div class="page-view" data-view="observed">
                
                <div class="players">   
                    <h2>Observed players</h2>
                    <div class="results"></div>
                </div>    
                
            </div>             
            
        </div>
            

    
    
    <script type="text/javascript">
        
        $(document).ready(function(){
    
            //switcher({ key: 'swipeable', class: 'icon-swipe',  value: true},function(el){ $(el).attr('data-value',true) }); // just for info
            button({ class: 'icon-btn icon-search2' }, function(el){            

                if ($('footer #popup .search').length){ 
                    $('footer #popup').html(''); 
                    $('.popup-btn').remove();
                    $('body').removeClass('with-popup');
                }else{ 
                    button({ class: 'icon-btn popup-btn icon-clear' }, function(){ $('.popup-btn').remove(); $('footer #popup').html(''); $('body').removeClass('with-popup no-blur'); });
                    $('footer #popup').html('<div class="popup active form"><input type="text" class="search" placeholder="Find by player name or nickname" /></div>'); 
                    $('body').addClass('with-popup no-blur');
                }            
            });
            
            $(document).on('keyup','.search',function(){
                $('.slick-initialized').slick('slickGoTo',0);
                get_all_players($(this).val());            
            });
            
            $(document).on('click','[data-action="observed"]',function(){
                $(this).toggleClass('icon-bookmark_outline').toogleClass('bookmark1');
            });
            
            $('.page-views').not('.slick-initialized').slick({
                arrows:false,
                dots:false,
                infinite: true,
                initialSlide:1
            }).on('beforeChange', (event, slick, currentSlide, nextSlide) => {
                if (currentSlide !== nextSlide) { }
            });               
            
            get_all_players();
            get_ranking_players();
            get_observed_players();
            
            
        });
        
        function get_all_players(search=null){
        
            $.ajax({
                url: config.api_url,
                data: { 
                    endpoint: '/players',
                    search:search
                },
                type: 'GET',
                dataType: 'JSON',
                cache: false,
                success: function(response){  
                    if (response.success === 'false') return;                    
                               
                    $('[data-view="all"] .results').html('');
                    $.each(response.players, function(i,player){
                        
                        let el = $('<div class="box"></div>')
                            .attr('data-username',player.username)
                            .append('<div class="avatar avatar-'+(player.avatar ? player.avatar : 'user')+'" style="color:'+(player.avatar_color ? player.avatar_color : 'var(--color-bg)')+'"></div>')
                            .append('<img src="/media/img/flags/PL.png" class="country" />')
                            //.append('<div class="icon-bookmark_outline" data-action="observed"></div>')
                            .append('<div class="title">'+player.username+'</div>')
                            .append('<div class="total">'+player.current_total+' $</div>')
                            .bind('click',function(){
                                location.href = '/wallet/'+player.username;
                            });
                        
                        $('[data-view="all"] .results').append(el);                        
                        
                    });
                }
            });
        
        }  
        
        function get_ranking_players(){
        
            $.ajax({
                url: config.api_url,
                data: { 
                    endpoint: '/players',
                    ranking:'highest-total-profit'
                },
                type: 'GET',
                dataType: 'JSON',
                cache: false,
                success: function(response){  
                    if (response.success === 'false') return;                    
                               
                    $('[data-view="highest-total-margin"] .results').html('');
                    var position = 1;
                    $.each(response.players, function(i,player){
                        
                        let el = $('<div class="box"></div>')
                            .attr('data-username',player.username)
                            .append('<div class="avatar avatar-'+(player.avatar ? player.avatar : 'user')+'" style="color:'+(player.avatar_color ? player.avatar_color : 'var(--color-bg)')+'"></div>')
                            .append('<img src="/media/img/flags/PL.png" class="country" />')
                            .append('<div class="position">'+(position++)+'</div>')
                            .append('<div class="title">'+player.username+'</div>')
                            .append('<div class="total">'+player.margin+' $</div>')
                            .bind('click',function(){
                                location.href = '/wallet/'+player.username;
                            });
                        
                        $('[data-view="highest-total-profit"] .results').append(el);                        
                        
                    });
                }
            });
        
        }
        
        function get_observed_players(){
        
            $.ajax({
                url: config.api_url,
                data: { 
                    endpoint: '/players/observed'
                },
                type: 'GET',
                dataType: 'JSON',
                cache: false,
                success: function(response){  
                    if (response.success === 'false') return;   
                    
                    if (!response.players || response.players.length === 0){
                        $('[data-view="observed"] h2').remove();
                        $('[data-view="observed"] .results').html('<div class="info-page"><div class="icon icon-clear"></div><h1>No Observed players</h1><p>This feature will be available soon.</p><div class="btn primary" onclick="$(\'.slick-initialized\').slick(\'slickGoTo\',0)">Find players</div></div>')
                        return;
                    }
                               
                    $('[data-view="highest-total-margin"] .results').html('');
                    var position = 1;
                    $.each(response.players, function(i,player){
                        
                        let el = $('<div class="box"></div>')
                            .attr('data-username',player.username)
                            .append('<div class="avatar avatar-'+(player.avatar ? player.avatar : 'user')+'" style="color:'+(player.avatar_color ? player.avatar_color : 'var(--color-bg)')+'"></div>')
                            .append('<img src="/media/img/flags/PL.png" class="country" />')
                            .append('<div class="position">'+(position++)+'</div>')
                            .append('<div class="title">'+player.username+'</div>')
                            .append('<div class="total">'+player.margin+' $</div>')
                            .bind('click',function(){
                                location.href = '/wallet/'+player.username;
                            });
                        
                        $('[data-view="highest-total-profit"] .results').append(el);                        
                        
                    });
                }
            });
        
        }
    
    </script>
    
    
    
    
    
    
        
<!--        
    
<div class="page players active">
    
    
    <div class="page-views players-page-views">
        <div class="page-view">
            <div class="box">                
                <h1>Top Margin Winners</h1>
            </div>
            <div class="players-container" data-ranking="0"></div>
        </div>
        <div class="page-view">
            <div class="box">
                <h1>Top Daily Gainers</h1>                
            </div>
            <div class="players-container" data-ranking="1"></div>
        </div>
        <div class="page-view">
            <div class="box">
                <h1>Highest Profit Makers</h1>                
            </div>
            <div class="players-container" data-ranking="2"></div>
        </div>
        <div class="page-view" data-ranking="3">
            <div class="box">
                <h1>Highest Profit Makers</h1>
                <p>This feature is under construction and its not available yet. Planned ranking here is for people who support community & financial markets investments. Knowledge Masters, Advice helpers & Experienced Players. </p>
            </div>
        </div>
    </div>     
    
</div>
<div class="player player-template hide">
    <div class="player-header">
        <div class="position"></div>
        <div class="info">
            <h3></h3>
            <span class="label last-seen"></span>
        </div>        
        <div class="results">
            <div  class="result1"></div>
            <span class="result2"></span>
            <span class="label result3"></span>            
        </div>      
    </div>
    <div class="player-body"></div>
</div>
<script type="text/javascript"> 
    $('.page-views').not('.slick-initialized').slick({
        arrows:false,
        dots:false,
        infinite: true
    }).on('beforeChange', (event, slick, currentSlide, nextSlide) => {
        if (currentSlide !== nextSlide) { 
            $('.changer-page-views .changer').removeClass('active'); 
            $('.changer[data-slick-position='+(nextSlide+1)+']').addClass('active');
            load_ranking(nextSlide);
        }
    });
    
    function load_ranking(ranking){
        console.log(ranking);       
        $.ajax({
            url: config.api_url,
            data: { endpoint: '/players/rankings', ranking:ranking },
            type: 'GET',
            dataType: 'JSON',
            cache:false,
            success: function(response){
                
                //console.log(response);                 
                var position = 1;
                $('.players-container[data-ranking="'+ranking+'"]').html('');
                
                $.each(response.wallets, function(i, wallet){
                    var player = $('.player-template').clone().removeClass('player-template').removeClass('hide').attr('data-wallet-id',wallet.id);
                    $(player).find('.player-header .info h3').html(wallet.username);
                    $(player).find('.player-header .info span').html('Last seen: '+wallet.last_seen);
                              
                    switch(ranking){
                        case 1:
                            $(player).find('.player-header .results .result1').html(wallet.margin_daily+ ' usd');
                            $(player).find('.player-header .results .result2').html(wallet.margin+ ' usd');
                            break;
                        case 2:
                            $(player).find('.player-header .results .result1').html(wallet.margin+ ' usd');
                            $(player).find('.player-header .results .result2').html(wallet.current_total + ' usd');
                            $(player).find('.player-header .results .result3').html(wallet.margin_percentage+'%');
                            break;
                        default:    
                            $(player).find('.player-header .results .result1').html(wallet.margin_percentage+'%');
                            $(player).find('.player-header .results .result2').html(wallet.current_total + ' usd');
                            $(player).find('.player-header .results .result3').html(wallet.margin+ ' usd');
                    }
                                        
                    
                    $(player).find('.player-header .position').html(position++);
                                                            
                    $.each(wallet.items, function(i, item){
                        $(player).find('.player-body').append(item.logo);
                    });
                    
                    $('.players-container[data-ranking="'+ranking+'"]').append($(player));
                });
                
            },
            error: function(response){
                console.log(response);
            }
        });
        
    };
    
    load_ranking(0);
    $(document).on('click', '.player', function(){
        var wallet_id=$(this).attr('data-wallet-id');
        window.location.href='/wallet/'+wallet_id;
    }); 
    
</script>
-->