    


    <link rel="stylesheet" href="/extensions/entities/media/css/entities.css?v=1.4" />
    
        <div class="page players active">

        <div class="page-views">
            <div class="page-view" data-view="all">
                
                <div class="players">   
                    <h2>All Players</h2>
                    <div class="results"></div>                                      
                </div>    
                
            </div>
            
            <div class="page-view" data-view="highest-total-profit">
                
                <div class="players">   
                    <h2>Highest Total Profit</h2>
                    <div class="results"></div>
                </div>    
                
            </div>   
            
            <div class="page-view" data-view="observed">
                
                <div class="players">   
                    <h2>Observed players</h2>
                    <div class="results"></div>
                </div>    
                
            </div>             
            
        </div>
            

    
    
    <script type="text/javascript">
        
        $(document).ready(function(){
    
            //switcher({ key: 'swipeable', class: 'icon-swipe',  value: true},function(el){ $(el).attr('data-value',true) }); // just for info
            button({ class: 'icon-btn icon-search2' }, function(el){            

                if ($('footer #popup .search').length){ 
                    $('footer #popup').html(''); 
                    $('.popup-btn').remove();
                    $('body').removeClass('with-popup');
                }else{ 
                    button({ class: 'icon-btn popup-btn icon-clear' }, function(){ $('.popup-btn').remove(); $('footer #popup').html(''); $('body').removeClass('with-popup no-blur'); });
                    $('footer #popup').html('<div class="popup active form"><input type="text" class="search" placeholder="Find by player name or nickname" /></div>'); 
                    $('body').addClass('with-popup no-blur');
                }            
            });
            
            $(document).on('keyup','.search',function(){
                $('.slick-initialized').slick('slickGoTo',0);
                get_all_players($(this).val());            
            });
            
            $(document).on('click','[data-action="observe"]',function(){
                
                var el      = $(this);
                var player  = $(el).parent('.box').attr('data-username');
                
                $.ajax({
                    url: config.api_url,
                    data: { 
                        endpoint: '/players/observed',
                        player: player
                    },
                    type: 'POST',
                    dataType: 'JSON',
                    cache: false,
                    success: function(response){  
                        if (response.success === false){ return; }
                        
                        $('[data-username="'+player+'"] [data-action="observe"]')
                            .removeClass('icon-bookmark_outline').addClass('icon-bookmark1')
                            .attr('data-action','stop-observe');
                    
                        get_observed_players();
                    }
                });                
                
            });

            $(document).on('click','[data-action="stop-observe"]',function(){
                
                var el      = $(this);
                var player  = $(el).parent('.box').attr('data-username');
                
                $.ajax({
                    url: config.api_url,
                    data: { 
                        endpoint: '/players/observed',
                        player: player
                    },
                    type: 'DELETE',
                    dataType: 'JSON',
                    cache: false,
                    success: function(response){  
                        if (response.success === false){ return; }

                        $('[data-username="'+player+'"] [data-action="stop-observe"]')
                            .addClass('icon-bookmark_outline').removeClass('icon-bookmark1')
                            .attr('data-action','observe');  

                        get_observed_players();
                    }
                });                
                
            });

            $('.page-views').not('.slick-initialized').slick({
                arrows:false,
                dots:false,
                infinite: true,
                initialSlide:2
            }).on('beforeChange', (event, slick, currentSlide, nextSlide) => {
                if (currentSlide !== nextSlide) { }
            });               
            
            get_all_players();
            get_ranking_players();
            get_observed_players();
            
            
        });
        
        function get_all_players(search=null){
        
            $.ajax({
                url: config.api_url,
                data: { 
                    endpoint: '/players',
                    search:search
                },
                type: 'GET',
                dataType: 'JSON',
                cache: false,
                success: function(response){  
                    if (response.success === 'false') return;                    
                               
                    $('[data-view="all"] .results').html('');
                    $.each(response.players, function(i,player){
                        
                        let el = $('<div class="view"></div>')                            
                            .append('<div class="avatar avatar-'+(player.avatar ? player.avatar : 'user')+'" style="color:'+(player.avatar_color ? player.avatar_color : 'var(--color-bg)')+'"></div>')
                            .append('<img src="/media/img/flags/PL.png" class="country" />')
                            .append('<div class="title">'+player.username+'</div>')
                            .append('<div class="total">'+player.current_total+' $</div>')
                            .bind('click',function(){
                                location.href = '/wallet/'+player.username;
                            });
                        let box = $('<div class="box"></div>')
                            .append(el)
                            .append('<div class="icon-bookmark_outline" data-action="observe"></div>')
                            .attr('data-username',player.username);
                        
                        $('[data-view="all"] .results').append(box);                        
                        
                    });
                }
            });
        
        }  
        
        function get_ranking_players(){
        
            $.ajax({
                url: config.api_url,
                data: { 
                    endpoint: '/players',
                    ranking:'highest-total-profit'
                },
                type: 'GET',
                dataType: 'JSON',
                cache: false,
                success: function(response){  
                    if (response.success === 'false') return;                    
                               
                    $('[data-view="highest-total-margin"] .results').html('');
                    var position = 1;
                    $.each(response.players, function(i,player){
                        
                        let el = $('<div class="view"></div>')                           
                            .append('<div class="avatar avatar-'+(player.avatar ? player.avatar : 'user')+'" style="color:'+(player.avatar_color ? player.avatar_color : 'var(--color-bg)')+'"></div>')
                            .append('<img src="/media/img/flags/PL.png" class="country" />')
                            .append('<div class="position">'+(position++)+'</div>')
                            .append('<div class="title">'+player.username+'</div>')
                            .append('<div class="total">'+player.margin+' $</div>')
                            .bind('click',function(){
                                location.href = '/wallet/'+player.username;
                            });
                        let box = $('<div class="box"></div>')
                            .append(el)
                            .append('<div class="icon-bookmark_outline" data-action="observe"></div>')
                            .attr('data-username',player.username);                            
                        
                        $('[data-view="highest-total-profit"] .results').append(box);                        
                        
                    });
                }
            });
        
        }
        
        function get_observed_players(){
        
            $.ajax({
                url: config.api_url,
                data: { 
                    endpoint: '/players/observed'
                },
                type: 'GET',
                dataType: 'JSON',
                cache: false,
                success: function(response){  
                    
                    console.log(response);
                    
                    if (response.success === 'false') return;   
                    
                    if (!response.players || response.players.length === 0){
                        $('[data-view="observed"] h2').remove();
                        $('[data-view="observed"] .results').html('<div class="info-page"><div class="icon icon-clear"></div><h1>No Observed players</h1><p>You don\'t observe any player yet.</p><div class="btn primary" onclick="$(\'.slick-initialized\').slick(\'slickGoTo\',0)">Find players</div></div>')
                        return;
                    }
                               
                    $('[data-view="observed"] .results').html('');
                    var position = 1;
                    $.each(response.players, function(i,player){
                        
                        let el = $('<div class="view"></div>')                            
                            .append('<div class="avatar avatar-'+(player.avatar ? player.avatar : 'user')+'" style="color:'+(player.avatar_color ? player.avatar_color : 'var(--color-bg)')+'"></div>')
                            .append('<img src="/media/img/flags/PL.png" class="country" />')
                            .append('<div class="position">'+(position++)+'</div>')
                            .append('<div class="title">'+player.username+'</div>')
                            .append('<div class="total">'+player.margin+' $</div>')
                            .bind('click',function(){
                                location.href = '/wallet/'+player.username;
                            });
                        let box = $('<div class="box"></div>')
                            .append(el)
                            .append('<div class="icon-bookmark1" data-action="stop-observe"></div>')
                            .attr('data-username',player.username);                             
                        
                        $('[data-view="observed"] .results').append(box);
                        
                        if ($('[data-username="'+player.username+'"]')){
                            $('[data-username="'+player.username+'"]').find('[data-action="observe"]')
                                .toggleClass('icon-bookmark_outline').toggleClass('icon-bookmark1')
                                .attr('data-action','stop-observe');
                        }
                        
                    });
                }
            });
        
        }
    
    </script>