    
    <div class="player-view">

        <div class="box overview">
            <div class="avatar-container"></div>
            <div class="username"></div>
            <div class="bio"></div>
            <div class="actions">            
            </div>
        </div>
        
        <div class="results">
            <div class="result box" data-result="margin">
                <div class="icon icon-auction"></div>
                <div class="value">0.00</div>
                <div class="title">Sold Profit</div>
            </div>
            <div class="result box" data-result="margin-percentage">
                <div class="icon icon-shopping_cart"></div>
                <div class="value">0.00</div>
                <div class="title">Profit %</div>
            </div>
            <div class="result box" data-result="purchased-total">
                <div class="icon icon-trophy"></div>
                <div class="value">0.00</div>
                <div class="title">Purchased Total</div>
            </div>
            <div class="result box" data-result="funds">
                <div class="icon icon-account_balance_wallet"></div>
                <div class="value funds-balance">0.00</div>
                <div class="title">Funds</div>
            </div>            
        </div>
        
        <div class="tabs">
            <div class="tab-container" data-type="active">
                <div class="tab-header">
                    <h2>Active items</h2>
                    <div class="expand icon-expand_more"></div>
                </div>
                <div class="tab-content">
                    <div class="slider-items-container">
                        <div class="slider-items"></div>            
                    </div>                    
                </div>
            </div>
            <div class="tab-container" data-type="sold-profit">
                <div class="tab-header">
                    <h2>Sold with profit</h2>
                    <div class="expand icon-expand_more"></div>
                </div>
                <div class="tab-content">
                    <div class="slider-items-container">
                        <div class="slider-items"></div>            
                    </div>                     
                </div>
            </div>  
            <div class="tab-container" data-type="sold-lost">
                <div class="tab-header">
                    <h2>Sold with lost</h2>
                    <div class="expand icon-expand_more"></div>
                </div>
                <div class="tab-content">
                    <div class="slider-items-container">
                        <div class="slider-items"></div>            
                    </div>                    
                </div>
            </div>             
        </div>  
        
        <div class="trophies box">
            <div class="trophy icon-security"       data-code="profile_completed" data-description="Added avatar, country representation, currency and info" data-title="Profile Completed"></div>
            <div class="trophy icon-account_balance_wallet" data-code="wallet_init" data-description="First items added to wallet" data-title="Wallet Initialized"></div>
            <div class="trophy icon-trending_up1"   data-code="profit_first" data-description="Earned first profit" data-title="First profit"></div>
            <div class="trophy icon-award-fill"     data-code="profit_25" data-description="25% margin in wallet" data-title="25%"></div>
            <div class="trophy icon-healthcare"     data-code="profit_50" data-description="50% margin in wallet" data-title="50%"></div>
            <div class="trophy icon-star-full"      data-code="profit_100" data-description="100% margin in wallet" data-title="100%"></div>
            <div class="trophy icon-technology"     data-code="profit_highest_100" data-description="100% margin in single transaction" data-title="100% highest margin"></div>
            
            <div class="trophy icon-stocks"      data-code="play_stocks"      data-description="Min. 1 transaction on stocks markets" data-title="Stocks play"></div>
            <div class="trophy icon-currencies"  data-code="play_forex"       data-description="Min. 1 transaction on currencies"     data-title="Currencies play"></div>
            <div class="trophy icon-commodities" data-code="play_commodities" data-description="Min. 1 transaction on commodities"    data-title="Commodities play"></div>
            <div class="trophy icon-crypto"      data-code="play_crypto"      data-description="Min. 1 transaction on crypto"         data-title="Crypto play"></div>
            <div class="trophy icon-indices"     data-code="play_indices"     data-description="Min. 1 transaction on indices"        data-title="Indices play"></div>
            <div class="trophy icon-trophy"      data-code="play_fantoken"    data-description="Min. 1 transaction on fan-tokens"     data-title="Fantoken play"></div>
                        
            <div class="trophy icon-logo"        data-code="contributor"      data-description="Available soon" data-title="Contributor"></div>
            <div class="trophy icon-trophy"      data-code="master"           data-description="Available soon" data-title="Master"></div>            
        </div>
    </div>

    <script type="text/javascript" src="/extensions/players/media/js/actions_player.js?v=1.0.3"></script> 
    <script type="text/javascript">

        function trophy(options,code){
            if (!options.target) options.target = '.trophies';
                        
            let trophy = $('<div class="trophy icon-'+options.class+' "></div>')
                .bind('click',function(){ 
                                        
                    //if (callback) callback(trophy); 
                });
            $(options.target).prepend(trophy);            
        }
        
        $(document).ready(function(){

            get_currencies(function(){    
                $.ajax({
                    url: config.api_url,
                    data: { 
                        endpoint: '/player',
                        username: mvc.controller
                    },
                    type: 'GET',
                    dataType: 'JSON',
                    cache: false,
                    success: function(response){  

                        if (response.success === false){                         
                            if (response.err === 404){
                                $('.player-view').html('<div class="info-page"><div class="icon icon-clear"></div><h1>Player not found</h1><p>Player you are trying to find doesn\'t exist or its on silent mode.</p><div class="btn primary" onclick="$(\'.slick-initialized\').slick(\'slickGoTo\',0)">Find players</div></div>');                           
                            }
                            return;                     
                        }                                              

                        if (config.debug) console.log(response);
                        var player = response.player;
                        var items  = response.items;
                        var trophies = response.trophies;
                        
                        button({ 
                             class: 'icon-btn icon-account_balance_wallet' }, 
                             function(){ 
                                 load_page('/wallet/'+player.username,true);                   
                             }
                        );                          
                        
                        // Overview
                        $('.overview').attr('data-username',player.username);

                        if (player.avatar_type){
                            $('.player-view .avatar-container').html("<img src='"+player.avatar+"' class='avatar-image' />");
                        }else{
                            $('.player-view .avatar-container').html('<div class="avatar avatar-'+(player.avatar ? player.avatar : 'user')+'" style="color:'+(player.avatar_color ? player.avatar_color : 'var(--color-bg)')+'"></div>');
                        }

                        $('.overview .username').text(player.username);
                        $('.overview .bio').text(player.bio);

                        let btn_results = '<div class="btn primary" onclick="load_page(\'/wallet/'+player.username+'\',true)">See Results</div>';
                        $(btn_results).bind('click',function(){
                            load_page('/wallet/'+player.username,true);
                        });

                        $('.overview .actions').append($(btn_results));

                        if (player.username !== me.username){
                            $('.overview .actions').prepend('<div class="icon-btn icon-'+(player.observed ? 'bookmark1' : 'bookmark_outline')+'" data-action="'+(player.observed ? 'stop-observe' : 'observe')+'"></div>');
                        }
                        if (player.country) $('.overview').prepend('<img src="/media/img/flags/'+player.country+'.svg" class="country" />');
                        
                        // Results                        
                        $('.results [data-result="margin"] .value').text(format_price(player.margin * currencies[settings.display_currency],2) + ' ' + settings.display_currency);
                        $('.results [data-result="margin-percentage"] .value').text(player.margin_percentage+' %');
                        $('.results [data-result="purchased-total"] .value').text(format_price(player.purchased_total * currencies[settings.display_currency],2) + ' ' + settings.display_currency);
                        $('.results [data-result="funds"] .value').text(format_price((player.funds ? player.funds : 1) * currencies[settings.display_currency],2) + ' ' + settings.display_currency);
                        
                        // Items
                        $.each(items, function(i,item){
                            
                            if (item.type === 'active' && !($('[data-type="active"] [data-symbol="'+item.symbol+'"][data-market="'+item.market+'"]')).length){
                                $('[data-type="active"]').addClass('active');
                                $('[data-type="active"] .slider-items').append('<div class="item" data-symbol="'+item.symbol+'" data-market="'+item.market+'" onclick="location.href=\'/entities/'+item.market+'/'+item.symbol+'\'">'+(item.logo ? '<img src="'+item.logo+'" class="logo" />' : '<div class="logo no-img">'+item.symbol+'</div>')+'</div>');
                            }
                            if (item.type === 'sold' && item.margin>=0 && !($('[data-type="sold-profit"] [data-symbol="'+item.symbol+'"][data-market="'+item.market+'"]')).length){
                                $('[data-type="sold-profit"]').addClass('active');
                                $('[data-type="sold-profit"] .slider-items').append('<div class="item" data-symbol="'+item.symbol+'" data-market="'+item.market+'" onclick="location.href=\'/entities/'+item.market+'/'+item.symbol+'\'">'+(item.logo ? '<img src="'+item.logo+'" class="logo" />' : '<div class="logo no-img">'+item.symbol+'</div>')+'</div>');
                            }
                            if (item.type === 'sold' && item.margin<0 && !($('[data-type="sold-lost"] [data-symbol="'+item.symbol+'"][data-market="'+item.market+'"]')).length){
                                $('[data-type="sold-lost"]').addClass('active');
                                $('[data-type="sold-lost"] .slider-items').append('<div class="item" data-symbol="'+item.symbol+'" data-market="'+item.market+'" onclick="location.href=\'/entities/'+item.market+'/'+item.symbol+'\'">'+(item.logo ? '<img src="'+item.logo+'" class="logo" />' : '<div class="logo no-img">'+item.symbol+'</div>')+'</div>');
                            }                            
                            
                        });
                        
                        if (trophies){
                            $.each(trophies, function(i,trophy){
                                $('.trophy[data-code="'+trophy.code+'"]').addClass('active');
                            });
                        }else{
                            $('.trophies').hide();
                        }
                        
                        //$('[data-result="profit"] .value').html()

                    }
                });
            });
        });
        
        $(document).off('click', '.trophy');
        $(document).on('click','.trophy',function(){
            $('body').addClass('with-popup').prepend('<div class="popup-info"><div class="popup-info-body"><div class="icon '+$(this).attr('class')+'"></div><div class="title">'+$(this).attr('data-title')+'</div><div class="description">'+$(this).attr('data-description')+'</div></div></div>');
        });

    </script>