    
    <div class="player-view">

        <div class="box overview">
            <div class="avatar-container"></div>
            <div class="username"></div>
            <div class="bio"></div>
            <div class="actions">            
            </div>
        </div>
        
        <div class="results">
            <div class="result box" data-result="profit">
                <div class="icon icon-auction"></div>
                <div class="value">20.00 usd</div>
                <div class="title">Profit</div>
            </div>
            <div class="result box" data-result="active-profit">
                <div class="icon icon-shopping_cart"></div>
                <div class="value">20 000.00 usd</div>
                <div class="title">Active Profit</div>
            </div>
            <div class="result box">
                <div class="icon icon-trophy"></div>
                <div class="value">300.00%</div>
                <div class="title">Highest Margin</div>
            </div>
            <div class="result box" data-result="funds">
                <div class="icon icon-account_balance_wallet"></div>
                <div class="value">15 000 usd</div>
                <div class="title">Funds</div>
            </div>            
        </div>

    </div>

    <script type="text/javascript" src="/extensions/players/media/js/actions_player.js?v=1.0.1"></script> 
    <script type="text/javascript">

        $(document).ready(function(){


                $.ajax({
                    url: config.api_url,
                    data: { 
                        endpoint: '/player',
                        username: mvc.controller
                    },
                    type: 'GET',
                    dataType: 'JSON',
                    cache: false,
                    success: function(response){  

                        if (response.success === false){                         
                            if (response.err === 404){
                                $('.player-view').html('<div class="info-page"><div class="icon icon-clear"></div><h1>Player not found</h1><p>Player you are trying to find doesn\'t exist or its on silent mode.</p><div class="btn primary" onclick="$(\'.slick-initialized\').slick(\'slickGoTo\',0)">Find players</div></div>');                           
                            }
                            return;                     
                        }

                        var player = response.player;
                        if (config.debug) console.log(player);

                        $('.overview').attr('data-username',player.username);

                        if (player.avatar_type){
                            $('.player-view .avatar-container').html("<img src='"+player.avatar+"' class='avatar-image' />");
                        }else{
                            $('.player-view .avatar-container').html('<div class="avatar avatar-'+(player.avatar ? player.avatar : 'user')+'" style="color:'+(player.avatar_color ? player.avatar_color : 'var(--color-bg)')+'"></div>');
                        }



                        $('.overview .username').text(player.username);
                        $('.overview .bio').text(player.bio);

                        let btn_results = '<div class="btn primary">See Results</div>';
                        $(btn_results).bind('click',function(){
                            load_page('/wallet/'+player.username,true);
                        });

                        $('.overview .actions').append($(btn_results));

                        if (player.username !== me.username){
                            $('.overview .actions').prepend('<div class="icon-btn icon-'+(player.observed ? 'bookmark1' : 'bookmark_outline')+'" data-action="'+(player.observed ? 'stop-observe' : 'observe')+'"></div>');
                        }
                        if (player.country) $('.overview').prepend('<img src="/media/img/flags/'+player.country+'.svg" class="country" />');
                        
                        //$('[data-result="profit"] .value').html()

                    }
                });

        });

    </script>