    

    
    <div class="my-account-container">
        <div class="my-account">
            <div class="banner">
                <div class="icon-logo1 banner-icon active"></div>
                <h1>Stocktok</h1>
            </div>
            <div class="my-account-page-container">
                <div class="my-account-page standard active">
                    
                    <div class="info">
                        <div class="info-inner init active">
                            <h2>Register/Login</h2>
                            <p>Put your nickname to check if you already have account.</p>
                        </div>
                        <div class="info-inner wrong-password">
                            <h2>Wrong password</h2>
                            <p>This password doesn't match to this username.</p>                            
                        </div>
                        <div class="info-inner wrong-password-noemail">
                            <h2>Wrong password</h2>
                            <p>This password doesn't match to this username.</p>                            
                        </div>
                        <div class="info-inner registration-info">
                            <h2>Set up password</h2>
                            <p>There is no such username. You can set up your password & create new account.</p>                            
                        </div>
                        <div class="info-inner login-info">
                            <h2>Login</h2>
                            <p>There is account for this username. Type your password and login.</p>                            
                        </div>
                        <div class="info-inner token-info">
                            <h2>Token Login</h2>
                            <p>App works on token mode (check config). You can log only into account related with your token.</p>                            
                        </div>
                        
                    </div>
                    <div class="registration-form">
                        <div class="field"><input id="username" type="text" placeholder="Your nickname" autocomplete="off" /></div>
                        <div class="field">
                            <input id="password" class="password" type="password" placeholder="Your password" />
                            <div class="show-password icon-remove_red_eye"></div>
                        </div>
                    </div>
                    <div class="actions">                                            
                        <div data-action="step2">
                            <span class="icon icon-fingerprint"></span>
                        </div>
                    </div>
                </div>
            </div> 
            <div class="tc">
                <div class="show active">^<br />Note</div>
                <div class="close label">Close <span class="icon-clear"></span></div>
            </div>
            <div class="tc-content hide-scroll">
                <div class="tc-content-inner">
                    <h1>Terms & Conditions</h1>
                    <h2>1. Stock prices</h2>
                    <p>Stock market engines process huge volume of transactions in every milisecond during trading hours. There is always a difference in price in almost every source/website. Prices are just indicative.</p>
                    <p>In stocktok there is up to 5min delay/gap in intraday pricing. Thats due to the fact that processing so much data in quick time requires technology investments. If you are interested in support please contact <a href="mailto:support@stocktok.online">support@stocktok.online</a></p>

                    <h2>2. Storing your data</h2>
                    <p>Stocktok stores only your wallets which are not related with you as a person.</p>
                    <p>Settings of your app & Google-Analytics data are stored in your browser. If you want to remove it, clear history of Stocktok in your browser's settings</p>

                    <h2>3. Access</h2>
                    <p>Wallet in stocktok is free and always will be. You don't have to pay anything or attach any credit-cards to get access to it.</p>
                </div>
            </div>
        </div>
    </div>
    
    <script type="text/javascript">
        
        $('footer').remove();
        $.getScript('/extensions/me/media/js/login.js?version='+config.version); 
        
    </script>